blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:blog_post_id>/', views.detail, name='detail')
]

homepage/urls.py
from django.urls import path

from . import views

app_name = "homepage"
urlpatterns = [
    path('', views.index, name="index"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("homepage.urls")),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils import timezone

class BlogPost(models.Model):
    title       = models.CharField(max_length=60)
    created_at  = models.DateTimeField(default=timezone.now, editable=False)
    modified_at = models.DateTimeField(default=timezone.now, editable=False)
    content     = models.TextField()
    
    def save(self, *args, **kwargs):
        timestamp = timezone.now()
        if self._state.adding:
            self.created_at = timestamp
        self.modified_at = timestamp
        super(BlogPost, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

homepage/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=256)
    creation_date = models.DateTimeField()
    content = models.TextField()

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import get_object_or_404, render

from .models import BlogPost

def index(request):
    blog_posts = BlogPost.objects.order_by('-created_at')
    context = {
        'blog_posts': blog_posts,
    }
    return render(request, 'blog/index.html', context)

def detail(request, blog_post_id):
    #TODO: clean the next and prev post queries up. it works for now, but
    # there has got to be a cleaner way to accomplish this
    blog_post = get_object_or_404(BlogPost, pk=blog_post_id)
    next_post = BlogPost.objects.filter(created_at__gt=blog_post.created_at).order_by('created_at').first() 
    prev_post = BlogPost.objects.filter(created_at__lt=blog_post.created_at).order_by('-created_at').first()
    if blog_post == next_post:
        next_post = None
    if blog_post == prev_post:
        prev_post = None
    context = {
        'blog_post': blog_post,
        'next_post': next_post,
        'prev_post': prev_post,
    }
    return render(request, 'blog/detail.html', context)

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'base.html')

posts/views.py
from django.shortcuts import render

from .models import Post

def index(request):
    posts = Post.objects.order_by('-creation_date')
    context = {
        'posts': posts
    }
    return render(request, 'posts/index.html', context)

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
    <title>{% block title %}TAP{% endblock %}</title>
  </head>
  <body>
    {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-light mb-3">
      <a class="navbar-brand" href="{% url 'blog:index' %}">TAP</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
          </li>
        </ul>
        <span class="navbar-text">
          Welcome
        </span>
      </div>
    </nav>
    {% endblock %}
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/detail.html
{% extends "base.html" %}

{% block title %}{{ blog_post.title }} - TAP{% endblock %}

{% block content %}
<div class="detail-container container">
  <div class="row">
    <div class="detail-title-card card col-md">
      <div class="timestamp">{{ blog_post.created_at }}</div>
      <div class="detail-title">{{ blog_post.title }}</div>
    </div>
  </div>
  <div class="row">
    <div class="detail-content-card card col-md">
      {% if blog_post.created_at < blog_post.modified_at %}
        <div class="timestamp font-weight-bold font-italic">Edited: {{ blog_post.modified_at }}</div>
      {% endif %}
      <div class="detail-content">{{ blog_post.content }}</div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block title %}Blog - TAP{% endblock %}

{% block content %}
<div class="blog-container container">
    {% for blog_post in blog_posts %}
      <div class="row">
        <div class="blog-card card col-md">
          <div class="timestamp">{{ blog_post.created_at }}</div>
          <div class="blog-title text-truncate">{{ blog_post.title }}</div>
          <a href="{% url 'blog:detail' blog_post.id %}" class="stretched-link"></a>
        </div>
      </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
    <title>{% block title %}TAP{% endblock %}</title>
  </head>
  <body>
    {% block nav %}
    <nav class="navbar-custom navbar navbar-expand-xl sticky-top">
      <a class="navbar-brand" href="{% url 'homepage:index' %}">TAP</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
          </li>
        </ul>
        <span class="navbar-text">
          Welcome
        </span>
      </div>
    </nav>
    {% endblock %}
    {% block content %}{% endblock %}
    <footer class="footer py-3">
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
  </body>
</html>